import type { NextPage } from 'next'
import Head from 'next/head'
import styled from 'styled-components'
import { motion } from 'framer-motion'
import { itemVariant, containerVariants } from '../utils/transitions'
import { useWindowResize } from '../hooks'
import { useTheme } from '../hooks/useTheme'


const Home: NextPage = () => {
  const { width } = useWindowResize()
  const { theme, toggleTheme } = useTheme()
  const formattedWidthSize = `${width}px`

  return (
    <Main>
      <Head>
        <title>index — prsnl</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
    <motion.div variants={containerVariants} initial="hidden" animate="show" >
      <Img src="/icon.svg" variants={itemVariant}></Img>
      <motion.h1 variants={itemVariant} style={{ color: 'var(--accent-color)' }}>Hello World 👋🏼</motion.h1>
      <motion.p variants={itemVariant} style={{ color: 'var(--accent-color)' }}>Hello from <Span>prsnl</Span> template 🔥🔥🔥</motion.p>
      <motion.p variants={itemVariant} style={{ color: 'var(--accent-color)' }}>Contains Next.js, Typescript, Styled Components, and Framer Motion</motion.p>
      <motion.p variants={itemVariant} style={{ color: 'var(--accent-color)' }}>Edit <Span>index.tsx</Span> to see changes 🚀</motion.p>
      <motion.p variants={itemVariant} style={{ color: 'var(--accent-color)' }}>Current window width size: <Span>{formattedWidthSize}</Span></motion.p>
      <Button variants={itemVariant} onClick={() => toggleTheme()}>Switch to { theme ? 'Dark' : 'Light' } Theme</Button>

    </motion.div>
    </Main>
  )
}

export default Home


const Main = styled.div`
  padding: 4rem 1rem;
`

const Span = styled.span`
  padding: .05rem .45rem;
  border-radius: .5rem;
  background-color: var(--button-bg-color);
  border: 1px solid var(--button-border-color);
  box-shadow: 0px 1px 2px var(--button-border-color);
  color: var(--button-text-color);
`

const Img = styled(motion.img)`
  width: 100px;
`

const Button = styled(motion.button)`
  padding: .25rem .45rem;
  border-radius: .5rem;
  background-color: var(--button-bg-color);
  border: 1px solid var(--button-border-color);
  box-shadow: 0px 1px 2px var(--button-border-color);
  color: var(--button-text-color);
  margin-right: .5rem;
  cursor: pointer;
`